language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install -qq -r requirements-test.txt tox
    - pip install -e .
script:
    - flake8 --ignore=E501 bottle_admin
    - py.test tests -vrsx --cov=bottle_admin
after_success:
    - pip install -qq coveralls
    - coveralls
