language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install -qq -r requirements-test.txt tox
    - pip install -e .
script:
    - flake8 --ignore=E501 bottle_admin
    - py.test bottle_admin -vrsx --cov bottle_admin
after-install:
    - pip install -qq coveralls
    - coveralls
